[package]
name = "sloth"
version = "0.1.0"
authors = ["Luke Schubert <lkschubert8@gmail.com>"]

[build-dependencies]
lalrpop ="0.15.2"

[dependencies]
lalrpop = "0.15.2"
regex = "0.2.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
